[changelog]
header = ""
body = """
{% if version -%}
## {{ version | trim_start_matches(pat="v") }}{% if previous.version %} ([compare](https://github.com/mahlquistj/octotype/compare/{{ previous.version }}...{{ version }})){% endif %}
[![Release Binary](https://github.com/mahlquistj/octotype/actions/workflows/release-binary.yml/badge.svg?tag={{ version }})](https://github.com/mahlquistj/octotype/actions/workflows/release-binary.yml)
[![Release Docs](https://github.com/mahlquistj/octotype/actions/workflows/release-docs.yml/badge.svg?tag={{ version }})](https://github.com/mahlquistj/octotype/actions/workflows/release-docs.yml)
---
{% else -%}
## Unreleased
{%- endif -%}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }}{% if commit.remote.username %} by @{{ commit.remote.username }}{% endif %}
{%- endfor %}
{% endfor %}

"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
  { message = "^feat", group = "âœ¨ Features"},
  { message = "^fix", group = "ğŸ› Bug Fixes"},
  { message = "^docs", group = "ğŸ“– Documentation"},
  { message = "^perf", group = "ğŸƒâ€â¡ï¸ Performance"},
  { message = "^refactor", group = "ğŸ§¹ Refactor"},
  { message = "^test", group = "ğŸ”¬ Testing"},
  { message = "^chore: bump version", skip = true},
  { message = "^chore: update flake inputs", skip = true},
  { message = "^chore", group = "ğŸ§© Miscellaneous"},
  { message = "^ci", group = "ğŸ‘· CI/CD"},
  { message = "^revert", group = "âª Reverts"},
]
filter_commits = true
